version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    pre_build:
        #commands:
        #- echo Restore started on `date`
        #- dotnet restore mgonzaga.ioc.netcore.sample.sln
        #finally:
        #  - echo This always runs even if the install command fails
    build:
        commands:
        - echo Build started on `date`
        - dotnet build mgonzaga.ioc.netcore.sample.sln
        - dotnet publish -c release -o ./build_output mgonzaga.ioc.netcore.sample.sln
artifacts:
    files:
        - ./build_output/**/*
        - scripts/**/*