version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 2.2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg build_without="development test" --build-arg rails_env="production" ./
artifacts:
  files: imagedefinitions.json