version: 0.2
phases:
pre_build:
commands:
- echo Restore started on `date`
- dotnet restore MGonzaga.IoC.NETCore.Sample.sln
build:
commands:
- echo Build started on `date`
- dotnet publish -c release -o ./build_output MGonzaga.IoC.NETCore.Sample.sln
artifacts:
files:
- backend-netcore-ioc-efcore-swagger/build_output/**/*
- scripts/**/*