version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 2.2
    build:
        commands:
        - echo Build started on `date`
        - docker build ./
artifacts:
    files:
        - ./app/**/*
        - scripts/**/*