// <auto-generated />
using System;
using MGonzaga.IoC.NETCore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MGonzaga.IoC.NETCore.Data.Migrations
{
    [DbContext(typeof(SysDataBaseContext))]
    [Migration("20190924014622_database-initial")]
    partial class databaseinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MGonzaga.IoC.NETCore.Domain.Models.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("ExpireDate");

                    b.Property<int>("ObjectId");

                    b.Property<int>("Type");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("MGonzaga.IoC.NETCore.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Blocked");

                    b.Property<bool>("ConfirmedEmail");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Locale");

                    b.Property<int>("LoginAttempts");

                    b.Property<DateTime?>("LoginLastDate");

                    b.Property<int>("OAuthProvider");

                    b.Property<string>("OAuthUId");

                    b.Property<string>("Password");

                    b.Property<string>("RolesNames");

                    b.Property<Guid?>("UniqueId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
